export const pregeneratedInterests = {
  toddlerFemale: ["Playing with stuffed animals or dolls",  "Playing Dress up",  "Art",  "Musical toys",  "Books with colorful illustrations",  "Building blocks and puzzles",  "Outdoor toys",  "Pretend kitchen and food sets",  "Learning"],
  toddlerMale: ["Building blocks or legos",  "Toy cars and trucks",  "Stuffed animals or plush toys",  "Musical instruments",  "Art supplies",  "Play kitchen and food sets",  "Outdoor toys",  "Puzzles and matching games",  "Books",  "Playing Dress-up"],
  elementaryFemale: [  "Arts and crafts",  "Dolls and doll accessories",  "Board games and puzzles",  "Reading",  "Doing science experiments",  "Playing Dress up",  "Musical instruments",  "Sports equipment",  "Collectible items",  "Cooking and baking"],
  elementaryMale: [  "Legos or building blocks",  "Superheros",  "Playing board games or card games",  "Sports",  "Science experiment kits",  "Remote control cars or helicopters",  "Art",  "Adventure stories",  "Educational computer games",  "Musical instruments",  "Outdoor toys",  "Puzzles",  "Stuffed animals or plush toys",  "Building model cars and planes",  "Dress-up costumes"],
  middleSchoolFemale: [  "Art",  "Jewelry Making",  "Reading",  "Board games or card games",  "Sports equipment",  "Musical instruments",  "Tech accessories",  "Cooking and baking",  "Science experiments",  "Fashion and beauty",  "Painting"],
  middleSchoolMale: [  "Sports",  "Video games",  "Action figures",  "Science experiment kits",  "Board games or card games",  "Reading",  "Art",  "LEGO sets or building toys",  "Camping",  "Listening to music"],
  teenageFemale: [  "Fashion and beauty",  "Music and concerts",  "Books and reading",  "Arts and craft",  "Outdoor activities",  "Tech gadgets",  "Sports equipment or apparel",  "Cooking and baking",  "Traveling",  "Jewelry and accessories"],
  teenageMale: [  "Sports",  "Video games",  "Music gear",  "Books",  "Technology gadgets",  "Clothing and fashion",  "Outdoor gear",  "Board games or card games",  "Art supplies",  "Kitchen gadgets",  "Fitness equipment",  "Photography equipment",  "Movie or TV show merchandise",  "DIY kits",  "Musical instrument accessories"],
  twentiesFemale: ["Yoga and fitness", "Cooking or baking", "Art supplies", "Travel accessories", "Skincare", "Coffee or tea", "Reading", "Sustainable fashion", "Hiking and camping", "Jewelry making", "Musical instruments", "Tech gadgets", "Home decor", "Language learning", "Knitting, crocheting, or embroidery"],
  twentiesMale: ["Fitness and exercise", "Sports", "Music", "Cooking and grilling", "Technology and gadgets", "Gaming", "Outdoor activities", "Traveling", "Fashion and grooming", "DIY projects and home improvement", "Photography and videography", "Cars and motorcycles", "Beer brewing or wine making", "Movies and TV shows", "Reading books or comics"],
  thirtiesFemale: ["Fitness and wellness", "Beauty and skincare", "Fashion and accessories", "Travel", "Books and reading", "Home decor", "Cooking and baking", "DIY projects", "Music and entertainment", "Personal development"],
  thirtiesMale: ["Sports", "Exercise and fitness", "Music", "Cooking and grilling", "Technology gadgets", "Outdoor gear", "Fashion and grooming products", "Travel", "Home decor items", "DIY tools and equipment"],
  fortiesFemale: ["Yoga or fitness", "Cooking or baking", "Painting or art", "Gardening or plants", "Reading", "Relaxing", "Travel accessories", "Wine tasting", "Home decor", "Jewelry", "Cleaning", "Technology gadgets", "Exploring the outdoors", "Musical instruments", "Cozy clothes"],
  fortiesMale: ["Golfing", "Fishing", "Hunting", "Barbecuing and Grilling", "Craft Beer Brewing", "Photography", "Traveling", "Home Improvement/DIY Projects", "Collecting Vintage Items", "Fitness/Working Out", "Sports", "Technology/Gadgets", "Cooking/Foodie Culture", "Music", "Motorcycles", "Cars"],
  fiftiesFemale: ["Gardening", "Cooking and recipes", "Fitness equipment", "Travel", "Art", "Sewing or knitting", "Music", "Home decor", "Reading self-help, history, or biographies", "Hiking, camping, or fishing"],
  fiftiesMale: ["Golfing", "Fishing", "Traveling", "Cooking or grilling", "Wine tasting", "Collecting sports memorabilia", "Reading books", "Watching movies or TV shows", "Photography", "Gardening or landscaping", "Home improvement projects", "Listening to music", "Hunting or shooting sports", "Playing poker or other card games", "Fitness and exercise", "Boating or sailing", "Classic cars and automobiles", "Technology and gadgets", "Fine art and paintings", "Craft beer tasting"],
  sixtiesFemale: ["Gardening tools or supplies", "Cooking or baking", "Travel", "Art supplies", "Music and instruments", "Jewelry or accessories", "Yoga or fitness", "Crossword puzzles or brain teasers", "Knitting/crocheting", "Wine tasting", "Scrapbooking"],
  sixtiesMale: ["Golf", "Fishing", "Gardening", "Cooking or grilling", "Wine tasting", "Traveling", "Reading", "Collecting", "Photography", "Woodworking or carpentry", "Painting or drawing", "Music", "Hiking or camping", "Watching sports", "Technology"],
  }


